// next-boardgamesite-frontend/src/app/login/page.tsx
"use client"
import {useContext, useState} from "react";
import {AppContext} from "@/state/AppContext";

import AccountService from "@/services/AccountService";
import {useRouter} from "next/navigation";


export default function Login() {
    const router = useRouter();

    const [email, setEmail] = useState("admin@eesti.ee");
    const [pwd, setPwd] = useState("Kala.maja1");

    const [pwdValidationError, setPwdValidationError] = useState("");
    const [emailValidationError, setEmailValidationError] = useState("");

    const {userInfo, setUserInfo} = useContext(AppContext)!;

    const validateAndLogin = async () => {
        if (email.length < 5) {
            setEmailValidationError("Invalid email length")
        } else {
            setEmailValidationError("")
        }
        if (pwd.length < 6) {
            setPwdValidationError("Invalid pwd length")
        } else {
            setPwdValidationError("")
        }
        const response = await AccountService.login(email, pwd);
        if (response.data) {
            setUserInfo(response.data);
            router.push('/')

        }
        if (response.errors && response.errors.length > 0) {
            setEmailValidationError(response.errors[0]);
        }
    }

    return (

        <div className="row">
            <div className="col-md-5">
                <h2>Log In</h2>
                <hr/>
                <div className={`text-danger error-input ${emailValidationError ? 'visible' : ''}`}
                     role="alert">{emailValidationError}</div>
                <div className="form-floating mb-3">
                    <input
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        type="email" id='email' className="form-control" autoComplete="email"
                        placeholder="name@example.com"/>
                    <label htmlFor="email" className="form-label">
                        Email
                    </label>
                </div>
                <div className={`text-danger error-input ${pwdValidationError ? 'visible' : ''}`}
                     role="alert">{pwdValidationError}</div>
                <div className="form-floating mb-3">
                    <input
                        value={pwd}
                        onChange={(e) => setPwd(e.target.value)}
                        type="password" id='password' className="form-control" autoComplete="current-password"
                        placeholder="password"/>
                    <label htmlFor="password" className="form-label">
                        Password
                    </label>
                </div>
                <div>
                    <button onClick={(e) => validateAndLogin()} className="w-100 btn btn-lg btn-primary">Login
                    </button>
                </div>
            </div>
        </div>
    );
}

// vue-demo/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import AccountService from "@/services/AccountService";
import {useAuthStore} from "@/stores/auth";


const authStore = useAuthStore();

let loginName = ref('');
let loginPassword = ref('');

let loginIsOngoing = ref(false);
let errors = ref<string[]>([]);

const doLogin = async () => {
  loginIsOngoing.value = true;

  const res = await AccountService.login(loginName.value, loginPassword.value);

  if (res.data) {
    authStore.jwt = res.data.jwt;
    authStore.refreshToken = res.data.refreshToken;
    authStore.userName = res.data.firstName + ' ' + res.data.lastName;
    authStore.isAuthenticated = true;
    errors.value = [];
  } else {
    errors.value = res.errors!;
  }

  loginIsOngoing.value = false;
}

</script>

<template>
  <h1>Log in</h1>
  <div class="row">
    <div class="col-md-6">
      <section>
        <form id="account" method="post">
          <hr />

          <div>{{ errors.join(',') }}</div>
          <div class="form-floating mb-3">
            <input v-model="loginName" class="form-control" autocomplete="username" aria-required="true"
                   placeholder="name@example.com" type="email" id="Input_Email" name="Input.Email" value="" />
            <label class="form-label" for="Input_Email">Email</label>
          </div>

          <div class="form-floating mb-3">
            <input v-model="loginPassword" class="form-control" autocomplete="current-password"
                   aria-required="true" placeholder="password" type="password" id="Input_Password"
                   name="Input.Password" />
            <label class="form-label" for="Input_Password">Password</label>
          </div>

          <div>
            <button @click.prevent="doLogin" id="login-submit" type="submit"
                    class="w-100 btn btn-lg btn-primary">{{ loginIsOngoing ? 'Wait...' : 'Do login' }}</button>
          </div>
        </form>
      </section>
    </div>

  </div>

</template>

<style scoped></style>
