// vue-webapp/src/views/Register.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import AccountService from '@/services/AccountService';
import {useAuthStore} from "@/stores/auth";

const router = useRouter();
const authStore = useAuthStore();

const email = ref('admin@eesti.ee');
const pwd = ref('Kala.maja1');
const firstName = ref('Jegor');
const lastName = ref('Stepanov');
const country = ref('Eesti');
const sex = ref('');
const  nickname = ref('Boss')

const emailValidationError = ref('');
const pwdValidationError = ref('');
const firstNameValidationError = ref('');
const lastNameValidationError = ref('');
const countryValidationError = ref('');
const sexValidationError = ref('');

const errors = ref("");

const isError = ref(false);

const validateAndRegister = async () => {
  isError.value = false;

  if (email.value.length < 5) {
    emailValidationError.value = 'Invalid email length';
    isError.value = true;
  } else {
    emailValidationError.value = '';
  }

  if (pwd.value.length < 6) {
    pwdValidationError.value = 'Invalid pwd length';
    isError.value = true;
  } else {
    pwdValidationError.value = '';
  }

  if (firstName.value.length < 1) {
    firstNameValidationError.value = 'Must be at least one character long first name!';
    isError.value = true;
  } else {
    firstNameValidationError.value = '';
  }

  if (lastName.value.length < 1) {
    lastNameValidationError.value = 'Must be at least one character long last name!';
    isError.value = true;
  } else {
    lastNameValidationError.value = '';
  }

  if (country.value.length < 1) {
    countryValidationError.value = 'Country name must be at least one character long!';
    isError.value = true;
  } else {
    countryValidationError.value = '';
  }

  if (sex.value.length === 0) {
    sexValidationError.value = 'Choose your sex!';
    isError.value = true;
  } else {
    sexValidationError.value = '';
  }

  if (!isError.value) {
    const response = await AccountService.register(email.value, pwd.value, firstName.value, lastName.value, country.value, sex.value, nickname.value);
    if (response.data) {
      authStore.jwt = response.data.token;
      authStore.refreshToken = response.data.refreshToken;
      authStore.userName = response.data.firstName + " " + response.data.lastName;
      authStore.isAuthenticated = true;
      router.push('/');
    } else if (response.errors && response.errors.length > 0) {
      emailValidationError.value = 'Email already exists!';
      errors.value = response.errors;
    }
  }
};
</script>

<style scoped>
.error-input {
  visibility: hidden;
}
.error-input.visible {
  visibility: visible;
}
</style>

<template>
  <div class="row">
    <div class="col-md-5">
      <h2>Registration</h2>
      <hr />
      <div v-if="emailValidationError" class="text-danger error-input" role="alert">{{ emailValidationError }}</div>
      <div class="form-floating mb-3">
        <input
            v-model="email"
            type="email"
            id="email"
            class="form-control"
            autocomplete="email"
            placeholder="name@example.com"
        />
        <label for="email" class="form-label">Email</label>
      </div>
      <div v-if="pwdValidationError" class="text-danger error-input" role="alert">{{ pwdValidationError }}</div>
      <div class="form-floating mb-3">
        <input
            v-model="pwd"
            type="password"
            id="password"
            class="form-control"
            autocomplete="current-password"
            placeholder="password"
        />
        <label for="password" class="form-label">Password</label>
      </div>
      <div v-if="firstNameValidationError" class="text-danger error-input" role="alert">{{ firstNameValidationError }}</div>
      <div class="form-floating mb-3">
        <input
            v-model="firstName"
            type="text"
            id="firstName"
            class="form-control"
            autocomplete="name"
            placeholder="Tamm"
        />
        <label for="firstName" class="form-label">First Name</label>
      </div>
      <div v-if="lastNameValidationError" class="text-danger error-input" role="alert">{{ lastNameValidationError }}</div>
      <div class="form-floating mb-3">
        <input
            v-model="lastName"
            type="text"
            id="lastName"
            class="form-control"
            autocomplete="family-name"
            placeholder="Saar">
        <label for="lastName" class="form-label">Last Name</label>
      </div>
        <div class="form-floating mb-3">
          <input
              v-model="nickname"
              type="text"
              id="nickname"
              class="form-control"
              autocomplete="family-name"
              placeholder="Boss"
          />
          <label for="nickname" class="form-label">NickName</label>
      </div>
      <div v-if="countryValidationError" class="text-danger error-input" role="alert">{{ countryValidationError }}</div>
      <div class="form-floating mb-3">
        <input
            v-model="country"
            type="text"
            id="country"
            class="form-control"
            autocomplete="country"
            placeholder="Estonia"
        />
        <label for="country" class="form-label">Country</label>
      </div>
      <div v-if="sexValidationError" class="text-danger error-input" role="alert">{{ sexValidationError }}</div>
      <div class="form-floating mb-3">
        <select id="sex" class="form-select" v-model="sex">
          <option value=""></option>
          <option value="male">Male</option>
          <option value="female">Female</option>
          <option value="other">Other</option>
          <option value="yes">Yes</option>
          <option value="no">No</option>
        </select>
        <label for="sex" class="form-label">Sex</label>
      </div>
      <div>
        <button @click="validateAndRegister" class="w-100 btn btn-lg btn-primary">Register</button>
      </div>
    </div>
  </div>
  {{errors}}
</template>

// next-boardgamesite-frontend/src/app/register/page.tsx
"use client"
import {useContext, useState} from "react";
import {AppContext} from "@/state/AppContext";

import AccountService from "@/services/AccountService";
import {redirect, useRouter} from "next/navigation";

export default function Register() {
    const router = useRouter();
    const [email, setEmail] = useState("admin@eesti.ee");
    const [pwd, setPwd] = useState("Kala.maja1");
    const [firstName, setFirstName] = useState("Jegor");
    const [lastName, setLastName] = useState("Stepanov");
    const [country, setCountry] = useState("Eesti");
    const [sex, setSex] = useState("");

    const [pwdValidationError, setPwdValidationError] = useState("");
    const [emailValidationError, setEmailValidationError] = useState("");
    const [firstNameValidationError, setFirstNameValidationError] = useState("");
    const [lastNameValidationError, setLastNameValidationError] = useState("");
    const [countryValidationError, setCountryValidationError] = useState("");
    const [sexValidationError, setSexValidationError] = useState("");

    const [isError, setError] = useState("False");


    const {userInfo, setUserInfo} = useContext(AppContext)!;

    const validateAndRegister = async () => {
        if (email.length < 5) {
            setEmailValidationError("Invalid email length");
            setError("True");
        } else {
            setEmailValidationError("");
        }
        if (pwd.length < 6) {
            setPwdValidationError("Invalid pwd length");
            setError("True");
        } else {
            setPwdValidationError("");
            setError("True");
        }
        if (firstName.length < 1) {
            setFirstNameValidationError("Must be at least one character long first name!");
            setError("True");
        } else {
            setFirstNameValidationError("");
        }
        if (lastName.length < 1) {
            setLastNameValidationError("Must be at least one character long last name!");
            setError("True");
        } else {
            setLastNameValidationError("");
        }
        if (country.length < 1) {
            setCountryValidationError("Country name must be at least one character long!");
            setError("True");
        } else {
            setCountryValidationError("");
        }
        if (sex.length === 0) {
            setSexValidationError("Choose your sex!");
            setError("True");
        } else {
            setSexValidationError("")
        }

        if (isError === "True") {
            setError("False")
        } else {
            const response = await AccountService.register(email, pwd, firstName, lastName, country, sex);
            if (response.data) {
                setUserInfo(response.data);
            }
            if (response.errors && response.errors.length > 0) {
                setEmailValidationError('Email already exist!');
            }
        }
    }

    if (userInfo) {
        router.push("/");
        return null;
    }
    else {

        return (

            <div className="row">
                <div className="col-md-5">
                    <h2>Registration</h2>
                    <hr/>
                    <div className={`text-danger error-input ${emailValidationError ? 'visible' : ''}`}
                         role="alert">{emailValidationError}</div>
                    <div className="form-floating mb-3">
                        <input
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            type="email" id='email' className="form-control" autoComplete="email"
                            placeholder="name@example.com"/>
                        <label htmlFor="email" className="form-label">
                            Email
                        </label>
                    </div>
                    <div className={`text-danger error-input ${pwdValidationError ? 'visible' : ''}`}
                         role="alert">{pwdValidationError}</div>
                    <div className="form-floating mb-3">
                        <input
                            value={pwd}
                            onChange={(e) => setPwd(e.target.value)}
                            type="password" id='password' className="form-control" autoComplete="current-password"
                            placeholder="password"/>
                        <label htmlFor="password" className="form-label">
                            Password
                        </label>
                    </div>
                    <div className={`text-danger error-input ${firstNameValidationError ? 'visible' : ''}`}
                         role="alert">{firstNameValidationError}</div>
                    <div className="form-floating mb-3">
                        <input
                            value={firstName}
                            onChange={(e) => setFirstName(e.target.value)}
                            type="firstName" id='firstName' className="form-control" autoComplete="name"
                            placeholder="Tamm"/>
                        <label htmlFor="firstName" className="form-label">
                            First Name
                        </label>
                    </div>
                    <div className={`text-danger error-input ${lastNameValidationError ? 'visible' : ''}`}
                         role="alert">{lastNameValidationError}</div>
                    <div className="form-floating mb-3">
                        <input
                            value={lastName}
                            onChange={(e) => setLastName(e.target.value)}
                            type="lastName" id='lastName' className="form-control" autoComplete="family-name"
                            placeholder="Saar"/>
                        <label htmlFor="lastName" className="form-label">
                            Last Name
                        </label>
                    </div>
                    <div className={`text-danger error-input ${countryValidationError ? 'visible' : ''}`}
                         role="alert">{countryValidationError}</div>
                    <div className="form-floating mb-3">
                        <input
                            value={country}
                            onChange={(e) => setCountry(e.target.value)}
                            type="country" id='country' className="form-control" autoComplete="country"
                            placeholder="Estonia"/>
                        <label htmlFor="country" className="form-label">
                            Country
                        </label>
                    </div>
                    <div className={`text-danger error-input ${sexValidationError ? 'visible' : ''}`}
                         role="alert">{sexValidationError}</div>
                    <div className="form-floating mb-3">
                        <select id="sex" className="form-select" value={sex} onChange={(e) => setSex(e.target.value)}>
                            <option value=""></option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">Other</option>
                            <option value="yes">Yes</option>
                            <option value="no">No</option>
                        </select>
                        <label htmlFor="sex" className="form-label">
                            Sex
                        </label>
                    </div>

                    <div>
                        <button onClick={(e) => validateAndRegister()}
                                className="w-100 btn btn-lg btn-primary">Register
                        </button>
                    </div>
                </div>
            </div>
        );
    }
}
